name: at_chat_flutter_example
description: Welcome to our SB Hacks workshop session! This app demonstrates how
  to use the at_chat_flutter plugin.
version: 0.0.1
homepage: https://atsign.com/

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  at_chat_flutter: ^3.0.1
  at_demo_data: ^1.0.0
  at_onboarding_flutter: ^3.0.0
  at_server_status: ^1.0.3
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
